CREATE TABLE IF NOT EXISTS Espece (
	idEsp SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nomEsp VARCHAR(100) NOT NULL,
	nbGenes SMALLINT UNSIGNED,
	nbProts SMALLINT UNSIGNED,
	nbTrans SMALLINT UNSIGNED,
	nbContigs SMALLINT UNSIGNED,
	pourcCodant TINYINT UNSIGNED,
	soucheEsp VARCHAR(10),
	PRIMARY KEY (idEsp)
)
ENGINE=INNODB;

INSERT INTO Espece 
VALUES (1,'Botrytis Cinerea',42,42,42,42,42,'B05.10');


CREATE TABLE IF NOT EXISTS Contigue (
	idContig CHAR(12) NOT NULL,
	idEsp SMALLINT UNSIGNED NOT NULL,
	seqContig TEXT,
	numContig DECIMAL(3,3),
	tailleContig SMALLINT,
	debContig SMALLINT,
	finContig SMALLINT,
	PRIMARY KEY (idContig),
	CONSTRAINT fk_idEspContigue
        FOREIGN KEY (idEsp)
        REFERENCES Espece(idEsp) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Gene (
	idGene CHAR(10) NOT NULL,
	idEsp SMALLINT UNSIGNED NOT NULL,
	seqGene TEXT,
	nomProtGene VARCHAR(100),
	tailleGene SMALLINT,
	debGene SMALLINT,
	finGene SMALLINT,
	brin CHAR(1),
	chromosome TINYINT UNSIGNED,
	PRIMARY KEY (idGene),
	CONSTRAINT fk_idEspGene
        FOREIGN KEY (idEsp)
        REFERENCES Espece(idEsp) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=INNODB;
